/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.util.Date;
import java.util.Calendar;
import java.util.ArrayList;

import modelo.Excel;
import modelo.TipoOrigen;
import modelo.Sismo;

/**
 *
 * @author javie
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    private static final String[] tituloColumnas = {"Fecha", "Hora", "Profundidad", "Origen", "Magnitud", "Latitud", "Longitud", "Ubicacion", "Provincia", "Marítimo"};
    private Excel excel;
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        excel = new Excel("excelTest.xlsx");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        maritimoBGroup = new javax.swing.ButtonGroup();
        mainPane = new javax.swing.JTabbedPane();
        verPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        fechaHoraTxt = new javax.swing.JLabel();
        profundidadTxt = new javax.swing.JLabel();
        origenTxt = new javax.swing.JLabel();
        magnitudTxt = new javax.swing.JLabel();
        latitudTxt = new javax.swing.JLabel();
        longitudTxt = new javax.swing.JLabel();
        ubicacionTxt = new javax.swing.JLabel();
        provinciaTxt = new javax.swing.JLabel();
        maritimoTxt = new javax.swing.JLabel();
        fechaHoraSpinner = new javax.swing.JSpinner();
        profundidadSpinner = new javax.swing.JSpinner();
        origenCbox = new javax.swing.JComboBox<>();
        magnitudSpinner = new javax.swing.JSpinner();
        latitudSpinner = new javax.swing.JSpinner();
        longitudSpinner = new javax.swing.JSpinner();
        ubicacionPane = new javax.swing.JScrollPane();
        ubicacionAreaTxt = new javax.swing.JTextArea();
        provinciaCbox = new javax.swing.JComboBox<>();
        siRButton = new javax.swing.JRadioButton();
        noRButton = new javax.swing.JRadioButton();
        eliminarButton = new javax.swing.JButton();
        agregarButton = new javax.swing.JButton();
        cambiosButton = new javax.swing.JButton();
        cargarButton = new javax.swing.JButton();
        estadisticasPanel = new javax.swing.JPanel();
        notificarPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        excel.extraerSismosDeArchivo();
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            excel.getSismosTexto(),
            tituloColumnas
        ));
        tabla.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        tabla.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabla);

        fechaHoraTxt.setText("Fecha y hora:");

        profundidadTxt.setText("Profundidad:");

        origenTxt.setText("Origen:");

        magnitudTxt.setText("Magnitud:");

        latitudTxt.setText("Latitud:");

        longitudTxt.setText("Longitud:");

        ubicacionTxt.setText("Ubicación:");

        provinciaTxt.setText("Provincia:");

        maritimoTxt.setText("Marítimo:");

        fechaHoraSpinner.setModel(new javax.swing.SpinnerDateModel());

        profundidadSpinner.setModel(new javax.swing.SpinnerNumberModel(0.0d, null, null, 0.1d));

        origenCbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Subducción", "Choque de placas", "Tectónico falla local", "Intra placa", "Deformación interna", "Indefinido" }));

        magnitudSpinner.setModel(new javax.swing.SpinnerNumberModel(0.0d, null, null, 0.1d));

        latitudSpinner.setModel(new javax.swing.SpinnerNumberModel(0.0d, -90.0d, 90.0d, 0.1d));

        longitudSpinner.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 360.0d, 0.1d));

        ubicacionAreaTxt.setColumns(20);
        ubicacionAreaTxt.setRows(5);
        ubicacionPane.setViewportView(ubicacionAreaTxt);

        provinciaCbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "San José", "Alajuela", "Cartago", "Heredia", "Puntarenas", "Guanacaste", "Limón", "Indefinido" }));

        maritimoBGroup.add(siRButton);
        siRButton.setText("Sí");

        maritimoBGroup.add(noRButton);
        noRButton.setSelected(true);
        noRButton.setText("No");

        eliminarButton.setText("Eliminar");
        eliminarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarButtonActionPerformed(evt);
            }
        });

        agregarButton.setText("Agregar");
        agregarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarButtonActionPerformed(evt);
            }
        });

        cambiosButton.setText("Realizar cambios");
        cambiosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiosButtonActionPerformed(evt);
            }
        });

        cargarButton.setText("Cargar");
        cargarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout verPanelLayout = new javax.swing.GroupLayout(verPanel);
        verPanel.setLayout(verPanelLayout);
        verPanelLayout.setHorizontalGroup(
            verPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(verPanelLayout.createSequentialGroup()
                .addGroup(verPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(verPanelLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(verPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(verPanelLayout.createSequentialGroup()
                                .addComponent(fechaHoraTxt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fechaHoraSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(verPanelLayout.createSequentialGroup()
                                .addGroup(verPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(origenTxt)
                                    .addComponent(profundidadTxt)
                                    .addComponent(magnitudTxt)
                                    .addComponent(latitudTxt)
                                    .addComponent(longitudTxt)
                                    .addComponent(ubicacionTxt)
                                    .addComponent(provinciaTxt))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(verPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(profundidadSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(origenCbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(magnitudSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(latitudSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(longitudSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ubicacionPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(provinciaCbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(verPanelLayout.createSequentialGroup()
                                .addComponent(maritimoTxt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(siRButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(noRButton))
                            .addGroup(verPanelLayout.createSequentialGroup()
                                .addComponent(agregarButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(eliminarButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cargarButton))))
                    .addGroup(verPanelLayout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(cambiosButton)))
                .addGap(53, 53, 53)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 818, Short.MAX_VALUE)
                .addContainerGap())
        );
        verPanelLayout.setVerticalGroup(
            verPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, verPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(verPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fechaHoraTxt)
                    .addComponent(fechaHoraSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(verPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(profundidadTxt)
                    .addComponent(profundidadSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(verPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(origenTxt)
                    .addComponent(origenCbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(verPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(magnitudTxt)
                    .addComponent(magnitudSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(verPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(latitudTxt)
                    .addComponent(latitudSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(verPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(longitudTxt)
                    .addComponent(longitudSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(verPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ubicacionTxt)
                    .addComponent(ubicacionPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(verPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(provinciaTxt)
                    .addComponent(provinciaCbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(verPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maritimoTxt)
                    .addComponent(siRButton)
                    .addComponent(noRButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 196, Short.MAX_VALUE)
                .addGroup(verPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregarButton)
                    .addComponent(eliminarButton)
                    .addComponent(cargarButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cambiosButton)
                .addGap(43, 43, 43))
            .addGroup(verPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
        );

        mainPane.addTab("Ver", verPanel);

        javax.swing.GroupLayout estadisticasPanelLayout = new javax.swing.GroupLayout(estadisticasPanel);
        estadisticasPanel.setLayout(estadisticasPanelLayout);
        estadisticasPanelLayout.setHorizontalGroup(
            estadisticasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );
        estadisticasPanelLayout.setVerticalGroup(
            estadisticasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 665, Short.MAX_VALUE)
        );

        mainPane.addTab("Estadísticas", estadisticasPanel);

        javax.swing.GroupLayout notificarPanelLayout = new javax.swing.GroupLayout(notificarPanel);
        notificarPanel.setLayout(notificarPanelLayout);
        notificarPanelLayout.setHorizontalGroup(
            notificarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );
        notificarPanelLayout.setVerticalGroup(
            notificarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 665, Short.MAX_VALUE)
        );

        mainPane.addTab("Notificar", notificarPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarButtonActionPerformed
        Sismo nuevoSismo = new Sismo();
        Calendar fechaHora = Calendar.getInstance();
        fechaHora.setTime((Date) fechaHoraSpinner.getValue());
        
        nuevoSismo.setFecha(fechaHora);
        nuevoSismo.setHora(fechaHora);
        nuevoSismo.setProfundidad((double) profundidadSpinner.getValue());
        nuevoSismo.setTipoOrigen((String) origenCbox.getSelectedItem());
        nuevoSismo.setMagnitud((double) magnitudSpinner.getValue());
        nuevoSismo.setLatitud((double) latitudSpinner.getValue());
        nuevoSismo.setLongitud((double) longitudSpinner.getValue());
        nuevoSismo.setDescripcionUbicacion(ubicacionAreaTxt.getText());
        nuevoSismo.setProvincia((String) provinciaCbox.getSelectedItem());
        nuevoSismo.setEsMaritimo(siRButton.isSelected());
        
        excel.agregarSismo(nuevoSismo);
        tabla.setModel(new javax.swing.table.DefaultTableModel(excel.getTablaAtributos(), tituloColumnas));
    }//GEN-LAST:event_agregarButtonActionPerformed

    private void eliminarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarButtonActionPerformed
        excel.eliminarSismo(tabla.getSelectedRow());
        excel.guardarDatos();
        tabla.setModel(new javax.swing.table.DefaultTableModel(excel.getTablaAtributos(), tituloColumnas));
    }//GEN-LAST:event_eliminarButtonActionPerformed

    private void cargarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarButtonActionPerformed
        excel.guardarDatos();
        tabla.setModel(new javax.swing.table.DefaultTableModel(excel.getTablaAtributos(), tituloColumnas));
    }//GEN-LAST:event_cargarButtonActionPerformed

    private void cambiosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiosButtonActionPerformed
        String[][] tablaAtributos = excel.getTablaAtributos();
        for (int i = 0; i < tabla.getRowCount(); i++) {
            for (int j = 0; j < Excel.columnas; j++) {
                String nuevoAtributo = (String) tabla.getValueAt(i, j);
                if (!tablaAtributos[i][j].equals(nuevoAtributo)) {
                    excel.setSismo(i, j, nuevoAtributo);
                }
            }
        }
        excel.guardarDatos();
        tabla.setModel(new javax.swing.table.DefaultTableModel(excel.getTablaAtributos(), tituloColumnas));
    }//GEN-LAST:event_cambiosButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarButton;
    private javax.swing.JButton cambiosButton;
    private javax.swing.JButton cargarButton;
    private javax.swing.JButton eliminarButton;
    private javax.swing.JPanel estadisticasPanel;
    private javax.swing.JSpinner fechaHoraSpinner;
    private javax.swing.JLabel fechaHoraTxt;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner latitudSpinner;
    private javax.swing.JLabel latitudTxt;
    private javax.swing.JSpinner longitudSpinner;
    private javax.swing.JLabel longitudTxt;
    private javax.swing.JSpinner magnitudSpinner;
    private javax.swing.JLabel magnitudTxt;
    private javax.swing.JTabbedPane mainPane;
    private javax.swing.ButtonGroup maritimoBGroup;
    private javax.swing.JLabel maritimoTxt;
    private javax.swing.JRadioButton noRButton;
    private javax.swing.JPanel notificarPanel;
    private javax.swing.JComboBox<String> origenCbox;
    private javax.swing.JLabel origenTxt;
    private javax.swing.JSpinner profundidadSpinner;
    private javax.swing.JLabel profundidadTxt;
    private javax.swing.JComboBox<String> provinciaCbox;
    private javax.swing.JLabel provinciaTxt;
    private javax.swing.JRadioButton siRButton;
    private javax.swing.JTable tabla;
    private javax.swing.JTextArea ubicacionAreaTxt;
    private javax.swing.JScrollPane ubicacionPane;
    private javax.swing.JLabel ubicacionTxt;
    private javax.swing.JPanel verPanel;
    // End of variables declaration//GEN-END:variables
}
